### ISSUE TITLE
Streamline redundent label changes

### ISSUE THREAD

**Issue by omesser** [bivas/rivi#50]
Not a critical issue but here is an example of rivi removing and adding the same label, which is redundant. It would be nicer if it would check what to remove, what to add, and leave what's still needed as is.
the offending label is `model changes (not-notified)`
<img width="737" alt="screen shot 2017-12-29 at 16 31 43" src="https://user-images.githubusercontent.com/18181802/34439391-3fad9c62-ecb6-11e7-8add-7a079a019385.png">

**Comment by bivas** [comment]
rivi does check for existing labels.
The issue here is a set of rules that might happen real fast (everything that happen in a small notification window will be folded by Github to single line).
I assume, that `model changes (not-notified)` was used to signal another rule to operate and it, in it's turn, removed it.
